"""empty message

Revision ID: 4ab7f33c38b7
Revises: 50d03151f484
Create Date: 2024-04-30 02:33:44.033844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ab7f33c38b7'
down_revision: Union[str, None] = '50d03151f484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('belbin_role',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Enum('chairman', 'closer', 'shaper', 'thinker', 'appraiser', 'collectivist', 'scout', 'executor', name='belbinrole'), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('belbin_role')
    # ### end Alembic commands ###
